In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv("/Users/Apple/ZAINUL_AI/DS/ML-Project/01 Breast Cancer/breast cancer.csv")

In [76]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [77]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [78]:
df.shape

(569, 33)

In [79]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [80]:
df.duplicated().sum()

np.int64(0)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [82]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [83]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [84]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Encoding

In [85]:
from sklearn.preprocessing import LabelEncoder

In [86]:
le = LabelEncoder()
df['diagnosis'] = le.fit_transform(df['diagnosis'])

In [87]:
df['diagnosis'].replace({0: 'B', 1: 'M'}, inplace=True)

df['diagnosis'].map({0: 'B', 1: 'M'})

/var/folders/2y/gg5t9kdn6lsgdpyzz8451qwc0000gn/T/ipykernel_22893/1782107203.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['diagnosis'].replace({0: 'B', 1: 'M'}, inplace=True)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
564    NaN
565    NaN
566    NaN
567    NaN
568    NaN
Name: diagnosis, Length: 569, dtype: object

In [88]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [89]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [90]:
df.shape

(569, 31)

In [91]:
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [92]:
X.shape

(569, 30)

In [93]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
X_train.shape

(455, 30)

In [42]:
y_train.shape

(455,)

In [43]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,0.08046,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,0.07398,...,26.680,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,0.06963,...,10.010,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,0.06329,...,12.250,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,0.06960,...,11.020,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,0.08980,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.14340,0.04786,0.2254,0.10840
106,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,0.06520,...,13.140,29.26,85.51,521.7,0.16880,0.26600,0.28730,0.12180,0.2806,0.09097
270,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.00625,0.1508,0.05376,...,14.910,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120
435,13.980,19.62,91.12,599.5,0.10600,0.11330,0.11260,0.06463,0.1669,0.06544,...,17.040,30.80,113.90,869.3,0.16130,0.35680,0.40690,0.18270,0.3179,0.10550
102,12.180,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.01770,0.1739,0.05677,...,13.340,32.84,84.58,547.8,0.11230,0.08862,0.11450,0.07431,0.2694,0.06878

In [44]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
X_train_scaled

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]], shape=(455, 30))

In [50]:
from sklearn.linear_model import LogisticRegression

In [52]:
lg = LogisticRegression()

In [53]:
lg.fit(X_train_scaled, y_train)

LogisticRegression()

In [55]:
y_pred = lg.predict(X_test_scaled)

In [56]:
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1])

In [57]:
from sklearn.metrics import accuracy_score

In [58]:
accuracy_score(y_test, y_pred)

0.9736842105263158

In [69]:
input_text = (2.13018192e-01, -5.90201273e-01,  2.78151024e-01,
         7.93179680e-02,  1.47083851e+00,  1.16919292e+00,
         1.00908719e+00,  1.07711474e+00,  1.26019637e+00,
         6.83612567e-01,  8.69160837e-02, -4.68975381e-01,
         6.31952291e-02,  2.34972050e-02, -1.33445566e-03,
        -2.93138093e-04, -8.45111045e-02,  1.29797207e-01,
        -5.57825655e-01,  2.28242912e-02,  5.35769651e-01,
         3.02768997e-01,  5.99822963e-01,  3.84469578e-01,
         2.44036784e+00,  1.26100069e+00,  9.36116234e-01,
         1.35650577e+00,  1.07793067e+00,  1.26945274e+00)

np_array = np.array(input_text).reshape(1, -1)

prediction = lg.predict(np_array)

if prediction[0] == 1:
    print("Cancerous")
else:
    print("Not Cancerous")

Cancerous

In [70]:
X_train[10:20:2]

array([[-4.97641900e-01,  6.13652740e-01, -4.98131305e-01,
        -5.31028146e-01, -5.76948242e-01, -1.74944245e-01,
        -3.62156219e-01, -2.84859000e-01,  4.33451646e-01,
         1.78182320e-01, -3.68449663e-01,  5.53104056e-01,
        -3.16711037e-01, -4.05246357e-01,  4.02575187e-02,
        -3.79552933e-02, -1.80430645e-01,  1.64789008e-01,
        -1.21709687e-01,  2.30793294e-01, -5.00440019e-01,
         8.19403673e-01, -4.69228376e-01, -5.33088327e-01,
        -4.91011709e-02, -4.16019255e-02, -1.49136531e-01,
         9.68178658e-02,  1.06176467e-01,  4.90353293e-01],
       [ 2.13018192e-01, -5.90201273e-01,  2.78151024e-01,
         7.93179680e-02,  1.47083851e+00,  1.16919292e+00,
         1.00908719e+00,  1.07711474e+00,  1.26019637e+00,
         6.83612567e-01,  8.69160837e-02, -4.68975381e-01,
         6.31952291e-02,  2.34972050e-02, -1.33445566e-03,
        -2.93138093e-04, -8.45111045e-02,  1.29797207e-01,
        -5.57825655e-01,  2.28242912e-02,  5.35769651e-01,
         3.02768997e-01,  5.99822963e-01,  3.84469578e-01,
         2.44036784e+00,  1.26100069e+00,  9.36116234e-01,
         1.35650577e+00,  1.07793067e+00,  1.26945274e+00],
       [-2.03185128e-01, -5.24493841e-01, -2.63517876e-01,
        -2.87623018e-01, -1.17733516e+00, -8.90227459e-01,
        -8.45146319e-01, -8.82465092e-01, -5.86321576e-01,
        -7.97964558e-01, -8.61291162e-01, -1.09079735e+00,
        -8.80770340e-01, -5.69071751e-01, -8.49876231e-01,
        -7.06727563e-01, -5.70337351e-01, -1.01952438e+00,
        -9.38814605e-01, -6.27303334e-01, -3.13173211e-01,
        -6.33115544e-01, -4.00237970e-01, -3.76488016e-01,
        -4.43773088e-01, -5.49855894e-01, -6.60687394e-01,
        -6.79070196e-01, -2.60014757e-01, -4.51409107e-01],
       [ 1.09638851e+00, -2.06627179e+00,  1.27258268e+00,
         9.77632373e-01,  1.62902429e+00,  3.31943081e+00,
         2.66062611e+00,  2.59927427e+00,  2.21441274e+00,
         2.21517730e+00,  2.45000976e+00, -5.49544289e-01,
         2.76990654e+00,  2.40182654e+00, -1.93247030e-01,
         1.25923694e+00,  6.51079660e-01,  6.32406704e-01,
         1.15846219e+00,  8.52185997e-01,  1.90281735e+00,
        -1.35442338e+00,  2.32458312e+00,  2.01395930e+00,
         1.33008201e+00,  2.66628739e+00,  2.09069131e+00,
         2.31736261e+00,  2.68853795e+00,  1.96497709e+00],
       [ 4.03079709e-02, -2.38197175e-01, -2.72580368e-02,
        -6.00124295e-02, -2.15592988e+00, -9.81044960e-01,
        -8.08109520e-01, -9.08505147e-01, -6.40952284e-01,
        -9.57647191e-01, -6.08153061e-01, -9.86205600e-01,
        -5.78682024e-01, -4.13511803e-01, -1.25105866e+00,
        -6.38397653e-01, -6.86188225e-01, -1.05785631e+00,
        -1.16912304e+00, -6.69328159e-01, -3.14260685e-03,
        -4.55054971e-02, -3.90881908e-02, -1.01026658e-01,
        -1.60827210e+00, -2.32762249e-01, -5.64592325e-01,
        -5.95857236e-01, -4.26465313e-01, -3.98683875e-01]])

In [71]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(lg, file)